language: cpp
addons:
  apt:
    packages:
      - make
      - cmake
      - libgtest-dev
      - libboost-all-dev
compiler:
  - gcc
  - clang
script: mkdir build && cd build && cmake .. && cd test && make
